[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 30

[[services]]
name = "web"
serviceType = "web"

[services.env]
PGHOST = "postgres.railway.internal"
PGPORT = "5432"
PGUSER = "${PGUSER}"
PGPASSWORD = "${PGPASSWORD}"
PGDATABASE = "${PGDATABASE}"
DATABASE_URL = "${DATABASE_URL}" 
