[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 30

[[services]]
name = "web"
serviceType = "web"
env = ["DATABASE_URL"]

[[services.envs]]
fromService = "postgresql"
key = "DATABASE_URL" 
