[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./main"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "web"
serviceType = "web"
env = ["DATABASE_URL"]

[[services.envs]]
fromService = "postgresql"
key = "DATABASE_URL" 
