name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Railway CLI
      run: curl -fsSL https://railway.app/install.sh | sh

    - name: Login to Railway
      run: railway login
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Link Project
      run: railway link
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Railway
      run: railway up --detach
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: View Logs
      run: railway logs
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 
